#! /usr/local/bin/php

<?php

use Symfony\Component\Console\Application;
use Acme\SayHelloCommand;

require 'vendor/autoload.php';

$app = new Application('Laracasts Demo', '1.0');

$app->add(new SayHelloCommand());

$app->run();
